(define (fib1 n)
  (cond ((<= n 0) 0)
        ((= n 1) 1)
        (else (+ (fib1 (- n 1)) (fib1 (- n 2))))))
(fib1 22)
(define (fib-iter a b n)
  (if (<= n 1) b (fib-iter b (+ a b) (- n 1))))
(define (fib n)
  (fib-iter 0 1 n))
(fib 22)
