(define (sqrt-iter guess last-guess x) 
  (if (good-enough? guess last-guess)
      guess
      (sqrt-iter (better-guess guess x) guess x)))
(define (good-enough? guess last-guess)
  (< (/ (abs (- guess last-guess)) guess) 0.001))
(define (better-guess guess x)
  (average guess (/ x guess)))
(define (average a b)
  (/ (+ a b) 2))
(define (square x) (* x x))
(define (sqrt x) (sqrt-iter 1.0 1.8e308 x))
(square 2)
(average 2.0 3)
(better-guess 1.0 2)
(good-enough? 1.4142 1.4143)
(good-enough? 1.5 2)
(sqrt 0.0001)
(sqrt 0.4e47)
(sqrt 0.4e307)
(sqrt 9)