(define (square x) (* x x))
(define (sum-of-squares x y) (+ (square x) (square y)))
(define (sum-of-squares-of-two-larger x y z)
  (cond ((and (>= x z) (>= y z)) (sum-of-squares x y))
        ((and (>= x y) (>= z y)) (sum-of-squares x z))
        (else (sum-of-squares y z))))
(sum-of-squares-of-two-larger 1 1 1)
(sum-of-squares-of-two-larger 1 2 3)
(sum-of-squares-of-two-larger 3 1 2)